### ISSUE TITLE
Docs. Note about rr queue `consume` config

### ISSUE THREAD

**Issue by gam6itko** [spiral/roadrunner-bridge#24]
Please add Note to documentation about this issue

I have  `rr` config below

```yaml
jobs:
    pool:
        command: "php app.php"
    # WE SAY - DO NOT CONSUME!!!
    consume: []
    pipelines:
        memory:
            driver: "memory"
            config:
                priority: 10
                prefetch: 10000
        notification:
            driver: amqp
            config:
                priority: 10
                prefetch: 100
                queue: "notification"
```

and  `config/queue.php` config 
```php
return [
    'connections' => [
        'roadrunner' => [
            'driver' => 'roadrunner',
            'default' => 'local',
            'pipelines' => [
                'local' => [
                    'connector' => new MemoryCreateInfo('local'),
                    // WE SAY - CONSUME IT!!!
                    'consume' => true,
                ],
            ],
        ],
    ],
];
```

The queue config from php will redefine `rr` consume config.
Actually  `rr` config will be like this
```yaml
jobs:
    pool:
        command: "php app.php"
    # WE SAY - CONSUME IT!!!
    consume: ["local"]
    pipelines:
        memory:
            driver: "memory"
            config:
                priority: 10
                prefetch: 10000
        notification:
            driver: amqp
            config: # NEW in 2.7
                priority: 10
                prefetch: 100
                queue: "notification"
```
